name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: build
    runs-on: ubuntu-latest

    steps:

      - name: Pre-run cleanup
        # Make sure the current directory is empty
        run: find . -delete
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install git python3

      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          pytest

      - name: Post-run cleanup
        if: always()
        run: find . -delete