name: Run lint

on:
  # Push to main or PR
  push:
    branches:
      - main
  pull_request:

jobs:
  linter:
    name: "Run linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint codebase
        run: |
          echo "LINT"
